export const techStack = [
    {
        name:'typescript',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/1200px-Typescript_logo_2020.svg.png'
    },
    {
        name:'javascript',
        img:'https://logosdownload.com/logo/javascript-logo-big.png'
    },
    {
        name:'react',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png'
    },
    {
        name:'next',
        img:'https://seeklogo.com/images/N/next-js-logo-7929BCD36F-seeklogo.com.png'
    },
    {
        name:'redux',
        img:'https://cdn-images-1.medium.com/max/1600/1*Vo5RDpNkOsfDn8sx06mthA.png'
    },
    {
        name:'nodejs',
        img:'https://seeklogo.com/images/N/nodejs-logo-FBE122E377-seeklogo.com.png'
    },
    {
        name:'express',
        img:'https://cdn.icon-icons.com/icons2/2699/PNG/512/expressjs_logo_icon_169185.png'
    },
    {
        name:'graphql',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/GraphQL_Logo.svg/2048px-GraphQL_Logo.svg.png'
    },
    {
        name:'psql',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png'
    },
    {
        name:'redis',
        img:'https://static-00.iconduck.com/assets.00/redis-plain-icon-2048x1748-fmvimw1g.png'
    },
    {
        name:'firebase',
        img:'https://cdn.icon-icons.com/icons2/2699/PNG/512/firebase_logo_icon_171157.png'
    },
    {
        name:'sass',
        img:'https://sass-lang.com/assets/img/styleguide/seal-color.png'
    },
    {
        name:'jest',
        img:'https://cdn.freebiesupply.com/logos/large/2x/jest-logo-png-transparent.png'
    },
    {
        name:'git',
        img:'https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png'
    },
    {
        name:'python',
        img:'https://clipart-library.com/images_k/python-logo-transparent/python-logo-transparent-5.png'
    },

]